### ISSUE TITLE
Deleting files before add a module ?

### ISSUE THREAD

**Issue by NicholasKuchiniski** [Rush/link-module-alias#10] opened 2019-03-20 18:08 UTC
I have a component folder that is i retrieve as @module, every time i run a yarn command like yarn add X the content from the ./components folder is erased ...

I think this is a bug so i making this issue.

**Comment by jsardev** [comment] 2019-03-23 00:05
Duplicate of #3

**Closed as completed** 2019-03-25 16:40 UTC
